prompt --application/pages/page_00110
begin
--   Manifest
--     PAGE: 00110
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.10.07'
,p_release=>'22.2.4'
,p_default_workspace_id=>8506563800894011
,p_default_application_id=>710
,p_default_id_offset=>84847035874187356
,p_default_owner=>'APPS'
);
wwv_flow_imp_page.create_page(
 p_id=>110
,p_name=>'Bulk Operations'
,p_alias=>'BULK-OPERATIONS'
,p_page_mode=>'MODAL'
,p_step_title=>'Bulk Operations'
,p_first_item=>'AUTO_FIRST_ITEM'
,p_autocomplete_on_off=>'OFF'
,p_group_id=>wwv_flow_imp.id(78949836938576475)  -- MAIN
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* HIDE DESC LABEL */',
'#P105_TASK_DESC_CONTAINER .t-Form-labelContainer {',
'  display: none;',
'}',
'#P105_TASK_DESC_CONTAINER .t-Form-itemWrapper {',
'  margin: 0 !important;',
'}',
'',
'',
'',
'/* HIDE EVERYTHING RELATED TO GRID */',
'#CHECKLIST .a-IG-header,',
'#CHECKLIST .a-GV-footer,',
'#CHECKLIST_ig_content_container .a-GV-hdr,',
'#CHECKLIST_ig_content_container .a-GV-footer,',
'#CHECKLIST_ig_content_container .js-stickyWidget-placeholder {',
'    display         : none !important;',
'}',
'#CHECKLIST_ig_content_container .a-IG {',
'    border          : 0 !important;',
'}',
'#CHECKLIST * {',
'    border          : 0 !important;',
'    box-shadow      : none !important;',
'    background      : transparent !important;',
'}',
'#CHECKLIST .CHECKLIST_BOX {',
'    margin-bottom   : -0.5rem;',
'}',
'#CHECKLIST .CHECKLIST_ITEM {',
'    border-bottom   : 1px dotted #333 !important;',
'    padding-left    : 0;',
'    padding-right   : 0;',
'}',
'#CHECKLIST .CHECKLIST_BOX .apex-item-single-checkbox {',
'    padding         : 3px 0 0 0.6rem;',
'}',
'#CHECKLIST .a-GV-cell.is-changed:not(.is-active):before,',
'#CHECKLIST .a-GV-row.is-updated .a-GV-selHeader:before {',
'    display         : none !important;',
'}',
'#CHECKLIST .a-GV-w-scroll {',
'    margin-left     : -0.6rem;',
'}',
'',
'',
'',
'/* RIGHT ALIGN USER COMMENTS */',
'#COMMENTS .t-Comments--chat li.OTHERS .t-Comments-icon {',
'    margin-left     : 2rem;',
'}',
'',
'/* FIX TRASH ICON ALIGNMENT */',
'span.t-Comments-actions {',
'    display         : block;',
'    float           : right;',
'    margin          : 0.25rem 0 -0.25rem;',
'}',
'',
''))
,p_page_template_options=>'#DEFAULT#'
,p_required_role=>wwv_flow_imp.id(71258645843174377)  -- MASTER - IS_USER
,p_dialog_width=>'1280'
,p_dialog_chained=>'N'
,p_protection_level=>'C'
,p_page_component_map=>'21'
,p_last_updated_by=>'DEV'
,p_last_upd_yyyymmddhh24miss=>'20220101000000'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(44285977800494711)
,p_plug_name=>'Bulk Operations [FORM]'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(70831193948975578)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(44286090683494712)
,p_plug_name=>'SOURCE'
,p_parent_plug_id=>wwv_flow_imp.id(44285977800494711)
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(70831193948975578)
,p_plug_display_sequence=>10
,p_plug_grid_column_span=>3
,p_plug_display_point=>'SUB_REGIONS'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(44286194908494713)
,p_plug_name=>'TARGET'
,p_parent_plug_id=>wwv_flow_imp.id(44285977800494711)
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(70831193948975578)
,p_plug_display_sequence=>20
,p_plug_new_grid_row=>false
,p_plug_grid_column_span=>3
,p_plug_display_point=>'SUB_REGIONS'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(44287803008494730)
,p_plug_name=>'FILTER_TASKS [GRID]'
,p_region_name=>'CHECKLIST'
,p_parent_plug_id=>wwv_flow_imp.id(44285977800494711)
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(70887424081975615)
,p_plug_display_sequence=>30
,p_plug_new_grid_row=>false
,p_plug_display_point=>'SUB_REGIONS'
,p_query_type=>'TABLE'
,p_query_table=>'TSK_P110_TASKS_V'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IG'
,p_ajax_items_to_submit=>'P110_SOURCE_CLIENT,P110_SOURCE_PROJECT,P110_SOURCE_BOARD,P110_SOURCE_STATUS,P110_SOURCE_SWIMLANE'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'Select Tasks'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(44289491525494746)
,p_name=>'TASK_ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TASK_ID'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>20
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_is_primary_key=>true
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(45280605118457921)
,p_name=>'TASK_NAME'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TASK_NAME'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>true
,p_item_type=>'NATIVE_DISPLAY_ONLY'
,p_heading=>'Task'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>40
,p_value_alignment=>'LEFT'
,p_value_css_classes=>'CHECKLIST_ITEM'
,p_attribute_05=>'HTML'
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(45280774487457922)
,p_name=>'TASK_SELECTED'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TASK_SELECTED'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_SINGLE_CHECKBOX'
,p_heading=>'Selected'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>10
,p_value_alignment=>'CENTER'
,p_value_css_classes=>'CHECKLIST_BOX'
,p_attribute_01=>'N'
,p_attribute_02=>'Y'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(45281115263457926)
,p_name=>'TASK_LINK'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TASK_LINK'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>true
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>50
,p_attribute_01=>'Y'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_is_primary_key=>false
,p_include_in_export=>false
);
wwv_flow_imp_page.create_interactive_grid(
 p_id=>wwv_flow_imp.id(44288066643494732)
,p_internal_uid=>44288066643494732
,p_is_editable=>true
,p_edit_operations=>'u'
,p_lost_update_check_type=>'VALUES'
,p_submit_checked_rows=>false
,p_lazy_loading=>false
,p_requires_filter=>false
,p_select_first_row=>false
,p_fixed_row_height=>true
,p_pagination_type=>'SCROLL'
,p_show_total_row_count=>false
,p_show_toolbar=>false
,p_toolbar_buttons=>null
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>false
,p_define_chart_view=>false
,p_enable_download=>false
,p_download_formats=>null
,p_fixed_header=>'PAGE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_imp_page.create_ig_report(
 p_id=>wwv_flow_imp.id(45255383118346884)
,p_interactive_grid_id=>wwv_flow_imp.id(44288066643494732)
,p_static_id=>'452554'
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_imp_page.create_ig_report_view(
 p_id=>wwv_flow_imp.id(45255509539346884)
,p_report_id=>wwv_flow_imp.id(45255383118346884)
,p_view_type=>'GRID'
,p_stretch_columns=>true
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(45284927172460376)
,p_view_id=>wwv_flow_imp.id(45255509539346884)
,p_display_seq=>2
,p_column_id=>wwv_flow_imp.id(44289491525494746)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>100
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(45337339504786868)
,p_view_id=>wwv_flow_imp.id(45255509539346884)
,p_display_seq=>3
,p_column_id=>wwv_flow_imp.id(45280605118457921)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(45338274859786872)
,p_view_id=>wwv_flow_imp.id(45255509539346884)
,p_display_seq=>1
,p_column_id=>wwv_flow_imp.id(45280774487457922)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>50
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(45351334306851429)
,p_view_id=>wwv_flow_imp.id(45255509539346884)
,p_display_seq=>4
,p_column_id=>wwv_flow_imp.id(45281115263457926)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(45281284999457927)
,p_plug_name=>'BUTTONS'
,p_parent_plug_id=>wwv_flow_imp.id(44285977800494711)
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(70831193948975578)
,p_plug_display_sequence=>40
,p_plug_new_grid_row=>false
,p_plug_new_grid_column=>false
,p_plug_display_point=>'SUB_REGIONS'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(108389736618010267)
,p_plug_name=>'Bulk Operations'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(70864195177975601)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_new_grid_row=>false
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(44286883866494720)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(45281284999457927)
,p_button_name=>'MAKE_CHANGES'
,p_button_static_id=>'MAKE_CHANGES'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(70970074101975671)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Make Changes'
,p_button_position=>'NEXT'
,p_button_css_classes=>'u-pullRight'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(45188962868165718)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(108389736618010267)
,p_button_name=>'CLOSE_DIALOG'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(70969417180975670)
,p_button_image_alt=>'Close Dialog'
,p_button_position=>'RIGHT_OF_TITLE'
,p_button_execute_validations=>'N'
,p_warn_on_unsaved_changes=>null
,p_button_css_classes=>'u-pullRight'
,p_icon_css_classes=>'fa-times'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44286206232494714)
,p_name=>'P110_SOURCE_STATUS'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(44286090683494712)
,p_prompt=>'Source Status'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_TASK_STATUSES'
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44286306349494715)
,p_name=>'P110_SOURCE_SWIMLANE'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_imp.id(44286090683494712)
,p_prompt=>'Source Swimlane'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_TASK_SWIMLANES'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44286437803494716)
,p_name=>'P110_SOURCE_CLIENT'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(44286090683494712)
,p_prompt=>'Source Client'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_CLIENTS'
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_read_only_when_type=>'ALWAYS'
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44286502131494717)
,p_name=>'P110_SOURCE_PROJECT'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(44286090683494712)
,p_prompt=>'Source Project'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_PROJECTS'
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_read_only_when_type=>'ALWAYS'
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44286665614494718)
,p_name=>'P110_SOURCE_BOARD'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(44286090683494712)
,p_prompt=>'Source Board'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_BOARDS'
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_read_only_when_type=>'ALWAYS'
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44287004908494722)
,p_name=>'P110_CLIENT_ID'
,p_is_required=>true
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(44286194908494713)
,p_item_default=>'P0_CLIENT_ID'
,p_item_default_type=>'ITEM'
,p_prompt=>'Client Id'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_CLIENTS_ALL'
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44287133015494723)
,p_name=>'P110_PROJECT_ID'
,p_is_required=>true
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(44286194908494713)
,p_item_default=>'P0_PROJECT_ID'
,p_item_default_type=>'ITEM'
,p_prompt=>'Project Id'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_PROJECTS_ALL'
,p_lov_display_null=>'YES'
,p_lov_cascade_parent_items=>'P110_CLIENT_ID'
,p_ajax_items_to_submit=>'P110_CLIENT_ID'
,p_ajax_optimize_refresh=>'Y'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44287282406494724)
,p_name=>'P110_BOARD_ID'
,p_is_required=>true
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(44286194908494713)
,p_item_default=>'P0_BOARD_ID'
,p_item_default_type=>'ITEM'
,p_prompt=>'Board Id'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_BOARDS_ALL'
,p_lov_display_null=>'YES'
,p_lov_cascade_parent_items=>'P110_PROJECT_ID'
,p_ajax_items_to_submit=>'P110_CLIENT_ID,P110_PROJECT_ID'
,p_ajax_optimize_refresh=>'Y'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44287369760494725)
,p_name=>'P110_STATUS_ID'
,p_is_required=>true
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(44286194908494713)
,p_item_default=>'P100_BOARD_TYPE'
,p_item_default_type=>'ITEM'
,p_prompt=>'Status Id'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_TASK_STATUSES_ALL'
,p_lov_display_null=>'YES'
,p_lov_cascade_parent_items=>'P110_BOARD_ID'
,p_ajax_items_to_submit=>'P110_CLIENT_ID,P110_PROJECT_ID,P110_BOARD_ID'
,p_ajax_optimize_refresh=>'Y'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'NO'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(44287496487494726)
,p_name=>'P110_SWIMLANE_ID'
,p_is_required=>true
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_imp.id(44286194908494713)
,p_item_default=>'P100_SWIMLANE_ID'
,p_item_default_type=>'ITEM'
,p_prompt=>'Swimlane Id'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_named_lov=>'LOV_TASK_SWIMLANES_ALL'
,p_lov_cascade_parent_items=>'P110_BOARD_ID'
,p_ajax_items_to_submit=>'P110_CLIENT_ID,P110_PROJECT_ID,P110_BOARD_ID'
,p_ajax_optimize_refresh=>'Y'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(70967669576975668)
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'NO'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(45209390022165756)
,p_name=>'CLOSE_DIALOG'
,p_event_sequence=>10
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_imp.id(45188962868165718)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'click'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(45209849904165757)
,p_event_id=>wwv_flow_imp.id(45209390022165756)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_DIALOG_CANCEL'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(44287653154494728)
,p_name=>'SOURCE_CHANGED'
,p_event_sequence=>20
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P110_SOURCE_CLIENT,P110_SOURCE_PROJECT,P110_SOURCE_BOARD,P110_SOURCE_STATUS,P110_SOURCE_SWIMLANE'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'change'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(44287759729494729)
,p_event_id=>wwv_flow_imp.id(44287653154494728)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(44287803008494730)
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(45281519596457930)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PROCESS_BULK_INIT'
,p_process_sql_clob=>'tsk_p110.process_bulk_init();'
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(45281063417457925)
,p_process_sequence=>20
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_imp.id(44287803008494730)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'PROCESS_BULK_TASK_FILTERS'
,p_attribute_01=>'PLSQL_CODE'
,p_attribute_04=>'tsk_p110.process_bulk_task_filters();'
,p_attribute_05=>'N'
,p_attribute_06=>'N'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_only_for_changed_rows=>'N'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(45281481702457929)
,p_process_sequence=>30
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PROCESS_BULK_REQUEST'
,p_process_sql_clob=>'tsk_p110.process_bulk_request();'
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp.component_end;
end;
/
