---
# ====== Application: Tasks ==================================
id: 710
identification: 
  name: Tasks
  alias: TASKS
  version: 2023-04-08

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: MASTER - OPEN_DOOR (TESTING ONLY) # 71255099014086701

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled
  session-timeout-url: '#LOGOUT_URL#'
  session-idle-timeout-url: '#LOGOUT_URL#'

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: APPS

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APP_NAME.'

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Black Text and White Background

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:HOME:&APP_SESSION.::&DEBUG.:::'
    page: HOME

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Menu # 70963306974975665
  template-options: 
  - '#DEFAULT#'
  - js-tabLike
  list-position: Top

navigation-bar: 
  implementation: List
  list: Navigation Bar # 98977601115303770
  list-template: Navigation Bar # 70957527289975660
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#WORKSPACE_FILES#master_app#MIN#.js?version=#APP_VERSION#'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#WORKSPACE_FILES#master_app#MIN#.css?version=#APP_VERSION#'

attributes: 
  theme: Universal Theme # 700
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Tasks

application-settings: 
- # ====== Application Setting: P0_CLIENT_ID ===================
  id: 35097556225810829
  identification: 
    name: P0_CLIENT_ID

  value: 
    value: Q
    required: false

  advanced: 
    on-upgrade-keep-value: true

- # ====== Application Setting: P0_PROJECT_ID ==================
  id: 35097785689811654
  identification: 
    name: P0_PROJECT_ID

  value: 
    value: PROJECT_ONE
    required: false

  advanced: 
    on-upgrade-keep-value: true

- # ====== Application Setting: P0_BOARD_ID ====================
  id: 35098015092813076
  identification: 
    name: P0_BOARD_ID

  value: 
    value: 1
    required: false

  advanced: 
    on-upgrade-keep-value: true

